### ISSUE TITLE
2 Реализовать логику сохранения настроек фильтра

### ISSUE THREAD

**Issue by pyclan88** [DecardCain21/practicum-android-diploma#111]
- Добавить локальное хранилище (например, SharedPreferences или Room) для сохранения:
  Уровня зарплаты.
  Флага «Не показывать без ЗП».
  Выбранной отрасли.
- Реализовать сохранение данных при изменении настроек.
- Настроить передачу параметров фильтрации в компонент поиска вакансий.
- Добавить обработку параметров в запросе (например, через ViewModel).
- Убедиться, что фильтр применяется корректно к результатам поиска.

**Comment by marsel-code** [comment]
В задании - В Data-слое реализован класс, выполняющий чтение и запись настроек параметров фильтрации поискового запроса в SharedPreferences.
