### ISSUE TITLE
На экране Фильтр кнопки применить и сбросить не работают

### ISSUE THREAD

**Issue by DecardCain21** [DecardCain21/practicum-android-diploma#163]
Кнопка «Применить» появляется, если пользователь указал фильтр, отличающийся от предыдущего. Нажатие на кнопку «Применить» приводит к сохранению выбранных настроек фильтра и применению фильтра для всех последующих запросов на поиск вакансий до изменения фильтра.

Кнопка «Сбросить» появляется, если пользователь указал хотя бы одно значение фильтров.

**Comment by sashkir7** [comment]
https://github.com/DecardCain21/practicum-android-diploma/pull/185
